/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class App {
	public static void main(String[] args) throws Exception {
		if (args.length != 3) {
			System.out.println("Usage: java -jar app.jar <htmlTemplate.html> <numeroEtudiants.txt> <encryptKey>");
			System.exit(1);
		}
		ExamenHTML examen = new ExamenHTML(args[0]);
		List<String> students = Files.readAllLines(Paths.get(args[1]));
		String key = args[2];
		GenAnoCode.saveAnoCodeToCsv(key, students, "anoCode.csv");
		for (int i = 0; i < students.size(); i++) {
			examen.addStudentPage(GenAnoCode.encrypt(key, students.get(i)), i + 1);
		}
		examen.saveExamToHtml("exam.html");
	}
}
